spring.application.name=springboot-mybatis-quickstart
# 数据库连接信息
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/web01
spring.datasource.username=root
spring.datasource.password=123456

# 开启mybatis的日志
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# 指定xml的mapper映射配置文件放置路径
mybatis.mapper-locations=classpath:mapper/*.xml
